# Generated by Django 2.0.2 on 2018-04-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('minutes', models.CharField(max_length=128)),
                ('instructions', models.CharField(max_length=10000)),
                ('ingredients', models.CharField(max_length=2048)),
                ('equipment', models.CharField(max_length=1024)),
                ('skills', models.CharField(max_length=1024)),
                ('dangers', models.CharField(max_length=512)),
            ],
        ),
    ]
